services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagelite
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - imagelite-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - imagelite-network

  sbootapp:
    build:
      dockerfile: Dockerfile
    container_name: imageliteapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - imagelite-network
    environment:
      - POSTGRES_HOST=db

networks:
  imagelite-network:
    driver: bridge